### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by didlich** [NetLogo/Play-Scraper#5]
I use a default play-scala project add the plugin and this to build.sbt

``` scala
lazy val root = (project in file("."))
  .enablePlugins(PlayScala)
  .enablePlugins(org.nlogo.PlayScrapePlugin)

scrapeRoutes ++= Seq("/landing")
```

this is the controller:

``` scala
package controllers
import javax.inject.{Inject, Singleton}
import play.api.mvc.{Action, Controller}

@Singleton
class LandingController @Inject() extends Controller {

  def index = Action {
    Ok(views.html.landing("Your new Landing Page is ready"))
  }

}
```

this is the template:

``` scala
@(message: String)

@main("Welcome to Landing Page") {
    @play20.welcome(message, style = "Scala")
}
```

then I call: scrapePlay
and I get:

[trace] Stack trace suppressed: run last compile:scrapePlay for the full output.
[error](compile:scrapePlay) java.lang.reflect.InvocationTargetException
[error] Total time: 1 s, completed Sep 10, 2016 1:09:17 PM

What I am doing wrong?

**Comment by TheBizzle** [comment]
It's not apparent to me that you're doing anything wrong.  I created [this GitHub project](https://github.com/TheBizzle/PlayScraperTestProject) to serve the closest test project I could produce to what you described here.  When I run `scrapePlay` on that project, it succeeds.  If you try cloning that project and running `scrapePlay` for yourself, does it succeed?

If so, then it seems likely that there's some problem with the configuration of your project.  Otherwise, it might have to do with the version of Java or SBT that is being used, or some other system configuration issue.

Also, you said it tells you:

> [trace] Stack trace suppressed: run last compile:scrapePlay for the full output.

Could you do as it says and run `last compile:scrapePlay` and show us the stack trace that that produces?

**Comment by didlich** [comment]
I tried your project PlayScraperTestProject, which compiles without problem. By the way the output under target/play-scrape looks strange. There is an index.html, which contains 404 and another file called landing.

OK.
I pushed a sample which integrates the Play-Scraper plugin with the compile error described above. The project was created using **activator-1.3.10-minimal** and from there selecting the **play-scala** template.

Below you can find the output of the compile error.
In the meantime I will try to compare your test project with my sample project to identify the differences.

this is the output of **last compile:scrapePlay**

``` scala
java.lang.NoSuchMethodException: controllers.ReverseAssets.at(java.lang.String)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at org.nlogo.StartServer$.pathForAsset(StartServer.scala:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.nlogo.ScrapeTasks$$anonfun$1.apply(ScrapeTasks.scala:56)
        at org.nlogo.ScrapeTasks$$anonfun$1.apply(ScrapeTasks.scala:56)
        at org.nlogo.ScrapeTasks$$anonfun$2$$anonfun$apply$1$$anonfun$apply$2.apply(ScrapeTasks.scala:62)
        at org.nlogo.ScrapeTasks$$anonfun$2$$anonfun$apply$1$$anonfun$apply$2.apply(ScrapeTasks.scala:61)
        at scala.Option.map(Option.scala:145)
        at org.nlogo.ScrapeTasks$$anonfun$2$$anonfun$apply$1.apply(ScrapeTasks.scala:61)
        at org.nlogo.ScrapeTasks$$anonfun$2$$anonfun$apply$1.apply(ScrapeTasks.scala:60)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at org.nlogo.ScrapeTasks$$anonfun$2.apply(ScrapeTasks.scala:60)
        at org.nlogo.ScrapeTasks$$anonfun$2.apply(ScrapeTasks.scala:58)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at org.nlogo.ScrapeTasks$.scrapeAssets(ScrapeTasks.scala:58)
        at org.nlogo.PlayScrapePlugin$$anonfun$17.apply(PlayScrapePlugin.scala:132)
        at org.nlogo.PlayScrapePlugin$$anonfun$17.apply(PlayScrapePlugin.scala:128)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:scrapePlay) java.lang.reflect.InvocationTargetException
```

**Comment by TheBizzle** [comment]
Odd.  Can you paste the contents of your `conf/routes` here?

**Comment by didlich** [comment]
sorry I forgot to paste the link to the project, here it is:
https://github.com/didlich/play-scraper-sample

**Comment by TheBizzle** [comment]
Okay, I understand the problem now.  As it turns out, we both used a slightly outdated version of Play-Scraper in our projects.  We used v0.7.2, and the latest is v0.7.3.  Yours fails because, in `conf/routes`, you're getting your assets from `Assets.versioned`, which didn't work with Play-Scraper before v0.7.3 .  The reason my test project worked is because I didn't get any assets from there, so it never had a chance to be tripped up by that.

So the solution is to the problem is two-fold:
1. Update `plugins.sbt` to use v0.7.3
2. You have to change your `play.crypto.secret` value in `conf/application.conf`
   - v0.7.3 also uses a newer version of Play—one that errors when `play.crypto.secret` isn't set how they want it to be.  If you look in your `conf/application.conf` file, you can find a definition of `play.crypto.secret` there, which might leave you confused (like I was).  The problem is that that value is set to `"changeme"`.  As far as Play is concerned, that's as good as not having the value set at all.  So you need to change it to something else.

After following both of those steps, things should work.

**Comment by didlich** [comment]
OK, followed your steps and there is no error any more. Thanks.

I have another question. The generated files in **target/play-scrape** are looking different than in real. When I use the **run** command and open the browser I get the styled web site with layout color etc. but if I open the generated index.html the styles and layout are not there.
Is this a desired behavior?

**Comment by TheBizzle** [comment]
The appearance is that of the page when it is run in production mode.  If you launch your web application with `start` rather than `run`, you'll see the page look the same as what gets scraped.

**Comment by didlich** [comment]
thanks, you are right
